export const CONTACT_REPOSITORY = Symbol('CONTACT_REPOSITORY');
export const CONTACT_NOTIFICATION_PORT = Symbol('CONTACT_NOTIFICATION_PORT');
export const CONTACT_SECURITY_CHALLENGE = Symbol('CONTACT_SECURITY_CHALLENGE');
