/* eslint-disable @typescript-eslint/no-explicit-any */
import type { TDocumentDefinitions, Content, TableCell } from 'pdfmake/interfaces';

const COLORS = {
  primary: '#2563EB',
  accent: '#F59E0B',
  success: '#16A34A',
  danger: '#DC2626',
  muted: '#6B7280',
  lightBg: '#F3F4F6',
  headerBg: '#1E40AF',
  white: '#FFFFFF',
};

export interface PdfMeta {
  title: string;
  subtitle?: string;
  locale: string;
  generatedBy?: string;
  date?: string;
}

export async function buildPdfBuffer(
  docDefinition: TDocumentDefinitions,
): Promise<Buffer> {
  // pdfmake server-side requires dynamic import for CJS compatibility
  const PdfPrinter = (await import('pdfmake')).default;

  const fonts = {
    Roboto: {
      normal: 'node_modules/pdfmake/build/vfs_fonts/Roboto-Regular.ttf',
      bold: 'node_modules/pdfmake/build/vfs_fonts/Roboto-Medium.ttf',
      italics: 'node_modules/pdfmake/build/vfs_fonts/Roboto-Italic.ttf',
      bolditalics: 'node_modules/pdfmake/build/vfs_fonts/Roboto-MediumItalic.ttf',
    },
  };

  const printer = new (PdfPrinter as any)(fonts);
  const pdfDoc = printer.createPdfKitDocument(docDefinition);

  return new Promise((resolve, reject) => {
    const chunks: Uint8Array[] = [];
    pdfDoc.on('data', (chunk: Uint8Array) => chunks.push(chunk));
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);
    pdfDoc.end();
  });
}

export function coverPage(meta: PdfMeta): Content[] {
  const dateStr = meta.date || new Date().toLocaleDateString(meta.locale === 'VI' ? 'vi-VN' : 'en-US');

  const cols: any[] = [
    {
      width: '*',
      text: [
        { text: meta.locale === 'VI' ? 'Ngày tạo: ' : 'Date: ', bold: true },
        dateStr,
      ],
      style: 'coverMeta',
      margin: [0, 15, 0, 0] as [number, number, number, number],
    },
  ];

  if (meta.generatedBy) {
    cols.push({
      width: '*',
      text: [
        { text: meta.locale === 'VI' ? 'Người tạo: ' : 'Generated by: ', bold: true },
        meta.generatedBy,
      ],
      style: 'coverMeta',
      alignment: 'right' as const,
      margin: [0, 15, 0, 0] as [number, number, number, number],
    });
  }

  return [
    { text: '', margin: [0, 80, 0, 0] as [number, number, number, number] },
    {
      canvas: [
        { type: 'rect', x: 0, y: 0, w: 515, h: 4, color: COLORS.primary },
      ],
    } as Content,
    { text: 'THÔNG THÁI SPACE', style: 'companyName', margin: [0, 30, 0, 5] as [number, number, number, number] },
    {
      text: 'Web & App Development • AI Solutions',
      style: 'companyTagline',
      margin: [0, 0, 0, 40] as [number, number, number, number],
    },
    { text: meta.title, style: 'coverTitle', margin: [0, 0, 0, 10] as [number, number, number, number] },
    {
      text: meta.subtitle || '',
      style: 'coverSubtitle',
      margin: [0, 0, 0, 30] as [number, number, number, number],
    },
    {
      canvas: [
        { type: 'rect', x: 0, y: 0, w: 515, h: 2, color: COLORS.lightBg },
      ],
    } as Content,
    { columns: cols } as Content,
    { text: '', pageBreak: 'after' as const },
  ];
}

export function sectionHeading(text: string, level: 1 | 2 | 3 = 1): Content {
  if (level === 1) {
    return {
      stack: [
        { text, style: 'h1', margin: [0, 15, 0, 5] as [number, number, number, number] },
        {
          canvas: [
            { type: 'rect', x: 0, y: 0, w: 100, h: 3, color: COLORS.primary },
          ],
          margin: [0, 0, 0, 10] as [number, number, number, number],
        },
      ],
    } as Content;
  }
  if (level === 2) {
    return { text, style: 'h2', margin: [0, 12, 0, 6] as [number, number, number, number] };
  }
  return { text, style: 'h3', margin: [0, 8, 0, 4] as [number, number, number, number] };
}

export function styledTable(
  headers: string[],
  rows: any[][],
  widths?: (string | number)[],
): Content {
  const headerRow = headers.map((h) => ({
    text: h,
    style: 'tableHeader',
    fillColor: COLORS.headerBg,
    color: COLORS.white,
  }));

  const dataRows = rows.map((row, i) =>
    row.map((cell: any) => {
      const base = typeof cell === 'string' || typeof cell === 'number'
        ? { text: String(cell) }
        : cell;
      return {
        ...base,
        fillColor: i % 2 === 0 ? COLORS.white : COLORS.lightBg,
        fontSize: 9,
      };
    }),
  );

  return {
    table: {
      headerRows: 1,
      widths: widths || headers.map(() => '*'),
      body: [headerRow, ...dataRows],
    },
    layout: {
      hLineWidth: () => 0.5,
      vLineWidth: () => 0.5,
      hLineColor: () => '#E5E7EB',
      vLineColor: () => '#E5E7EB',
      paddingLeft: () => 6,
      paddingRight: () => 6,
      paddingTop: () => 4,
      paddingBottom: () => 4,
    },
    margin: [0, 5, 0, 10] as [number, number, number, number],
  } as Content;
}

export function bulletList(items: string[]): Content {
  return {
    ul: items.map((item) => ({ text: item, margin: [0, 2, 0, 2] as [number, number, number, number] })),
    margin: [0, 5, 0, 10] as [number, number, number, number],
  };
}

export function keyValueRow(key: string, value: string): Content {
  return {
    columns: [
      { width: 150, text: key, bold: true, fontSize: 10, color: COLORS.muted },
      { width: '*', text: value, fontSize: 10 },
    ],
    margin: [0, 3, 0, 3] as [number, number, number, number],
  } as Content;
}

export function progressBar(percent: number): Content {
  const barWidth = 400;
  const filled = Math.round((percent / 100) * barWidth);
  const barColor =
    percent >= 75 ? COLORS.success : percent >= 40 ? COLORS.accent : COLORS.danger;

  return {
    stack: [
      {
        canvas: [
          { type: 'rect', x: 0, y: 0, w: barWidth, h: 16, r: 4, color: COLORS.lightBg },
          { type: 'rect', x: 0, y: 0, w: Math.max(filled, 4), h: 16, r: 4, color: barColor },
        ],
      },
      {
        text: `${percent}%`,
        fontSize: 9,
        bold: true,
        color: barColor,
        alignment: 'right' as const,
        margin: [0, 2, 0, 0] as [number, number, number, number],
      },
    ],
    margin: [0, 5, 0, 10] as [number, number, number, number],
  } as Content;
}

export const defaultStyles = {
  companyName: { fontSize: 22, bold: true, color: COLORS.primary },
  companyTagline: { fontSize: 11, color: COLORS.muted, italics: true },
  coverTitle: { fontSize: 26, bold: true, color: '#111827' },
  coverSubtitle: { fontSize: 14, color: COLORS.muted },
  coverMeta: { fontSize: 10, color: COLORS.muted },
  h1: { fontSize: 16, bold: true, color: COLORS.primary },
  h2: { fontSize: 13, bold: true, color: '#1F2937' },
  h3: { fontSize: 11, bold: true, color: '#374151' },
  tableHeader: { fontSize: 9, bold: true },
  bodyText: { fontSize: 10, lineHeight: 1.4, color: '#374151' },
};

export function defaultFooter(meta: PdfMeta) {
  return (currentPage: number, pageCount: number): Content => ({
    columns: [
      {
        text: 'Thông Thái Space',
        fontSize: 8,
        color: COLORS.muted,
        margin: [40, 0, 0, 0] as [number, number, number, number],
      },
      {
        text: `${meta.locale === 'VI' ? 'Trang' : 'Page'} ${currentPage} / ${pageCount}`,
        fontSize: 8,
        color: COLORS.muted,
        alignment: 'right' as const,
        margin: [0, 0, 40, 0] as [number, number, number, number],
      },
    ],
    margin: [0, 10, 0, 0] as [number, number, number, number],
  } as Content);
}
