import { Injectable } from '@nestjs/common';
import {
  Document,
  HeadingLevel,
  ImageRun,
  Packer,
  Paragraph,
  TextRun,
} from 'docx';
import { Resvg } from '@resvg/resvg-js';

@Injectable()
export class DocxGeneratorService {
  async generateArchitectureReport(input: {
    title?: string;
    description: string;
    svg: string;
    generatedAt?: Date;
  }): Promise<Buffer> {
    const generatedAt = input.generatedAt ?? new Date();
    let pngBuffer: Buffer | null = null;

    try {
      const resvg = new Resvg(input.svg, {
        fitTo: {
          mode: 'width',
          value: 900,
        },
      });
      pngBuffer = resvg.render().asPng();
    } catch {
      // Keep report generation resilient in environments where SVG rendering can fail.
      pngBuffer = null;
    }

    const descriptionParagraphs = input.description
      .split(/\n\s*\n/g)
      .map((paragraph) => paragraph.trim())
      .filter(Boolean)
      .map((paragraph) => new Paragraph(paragraph));

    const doc = new Document({
      sections: [
        {
          children: [
            new Paragraph({
              text: input.title || 'Architecture Report',
              heading: HeadingLevel.TITLE,
            }),
            new Paragraph({
              children: [
                new TextRun({ text: 'Generated by Thong Thai Space AI Agent' }),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({ text: `Date: ${generatedAt.toISOString()}` }),
              ],
            }),
            new Paragraph({ text: '' }),
            new Paragraph({
              text: 'Architecture Description',
              heading: HeadingLevel.HEADING_1,
            }),
            ...descriptionParagraphs,
            new Paragraph({ text: '' }),
            new Paragraph({
              text: 'Architecture Diagram',
              heading: HeadingLevel.HEADING_1,
            }),
            ...(pngBuffer
              ? [
                  new Paragraph({
                    children: [
                      new ImageRun({
                        type: 'png',
                        data: pngBuffer,
                        transformation: {
                          width: 900,
                          height: 600,
                        },
                      }),
                    ],
                  }),
                ]
              : [
                  new Paragraph(
                    'Diagram preview is unavailable in this environment. The SVG source is included below.',
                  ),
                  new Paragraph({ text: input.svg }),
                ]),
          ],
        },
      ],
    });

    return Packer.toBuffer(doc);
  }
}
